let products = [
    {
        "id": 1001,
        "image": "",
        "subject": "Rizz 101",
        "price": $500,
        "location": "Lecture Hall GK17",
        "description": "",
        "availability": "",
    },
    {
        "id": 1002,
        "image": "",
        "subject": "",
        "price": 0,
        "location": "",
        "description": "",
        "availability": "",
    },
    {
        "id": 1003,
        "image": "",
        "subject": "",
        "price": 0,
        "location": "",
        "description": "",
        "availability": "",
    },
    {
        "id": 1004,
        "image": "",
        "subject": "",
        "price": 0,
        "location": "",
        "description": "",
        "availability": "",
    },
    {
        "id": 1005,
        "image": "",
        "subject": "",
        "price": 0,
        "location": "",
        "description": "",
        "availability": "",
    },
    {
        "id": 1006,
        "image": "",
        "subject": "",
        "price": 0,
        "location": "",
        "description": "",
        "availability": "",
    },
    {
        "id": 1007,
        "image": "",
        "subject": "",
        "price": 0,
        "location": "",
        "description": "",
        "availability": "",
    },
    {
        "id": 1008,
        "image": "",
        "subject": "",
        "price": 0,
        "location": "",
        "description": "",
        "availability": "",
    },
    {
        "id": 1009,
        "image": "",
        "subject": "",
        "price": 0,
        "location": "",
        "description": "",
        "availability": "",
    },
    {
        "id": 1010,
        "image": "",
        "subject": "",
        "price": 0,
        "location": "",
        "description": "",
        "availability": "",
    }
]